### PR TITLE
Info Buttons to Describe config params

### PR DESCRIPTION
**Pull request by youralien**
Summary:

- Added qtawesome which gives nice font awesome icons like 'fa:info'
- Refactored common functionality to a configGuiWidget class, in which
  configGui_feature and configGui_object inherit
- Added gridRowHelper method to product the labelX, infoX, inputX
  attributes
- Copied descriptions of these parameters from last years SCOPE software
  user guide.
- Increased message_dialog default size, and then resizes according to text
  input.

One of the parameters on the feature config page
screen shot 2017-02-20 at 4 53 13 pm

Parameters for the road user object config page
screen shot 2017-02-20 at 4 53 25 pm

### CODE REVIEW

**Comment by youralien** [comment]
I need to rebase 'dev' when https://github.com/santosfamilyfoundation/SantosGUI/pull/68 is merged into dev.  

Also, this required either a `pip install qtawesome` or `conda install qtawesome`.  I decided not to do a requirements.txt file in this commit yet.

**Comment by segerphilip** [comment]
Why are you not planning on a requirements.txt file yet? It makes life easier

**Review by dcelik — CHANGES_REQUESTED** [review]
Two things: 
1. I agree with @segerphilip that we should keep track of our different pip installs, whether that be with a requirements.txt or by adding them to the README.
2. While this doesn't need to be changed, I think this could be improved with hover over info instead of clicked pop ups.

Other than that looks good.

**Review by dcelik — APPROVED** [review]
Looks good, not 100% sure if versioning is correct but at least it is documented for testing now.

**Pull request merged**
