### PR TITLE
Fixed GUI elements to display nicely on all platforms we support

### PR DESCRIPTION
**Pull request by youralien**
For reviewers, can you pull and see if the layout displays similarly for you?

screen shot 2017-02-13 at 5 43 53 pm
screen shot 2017-02-13 at 5 44 05 pm

### CODE REVIEW

**Comment by runnersaw** [comment]
Oops, didn't know this relied on the other open PR. I'd say change this to dev when you have a chance.

**Review by runnersaw — APPROVED** [review]
Looks great! Tested on Windows

**Comment by youralien** [comment]
@runnersaw mind testing one more time?  I added one more commit fixing the new_project.ui file too.
screen shot 2017-02-13 at 11 10 59 pm

**Comment by runnersaw** [comment]
Still looks good!

**Pull request merged**
