### PR TITLE
Create a message_helper to show alerts to the user

### PR DESCRIPTION
**Pull request by runnersaw**
Creates `message_helper` to show messages to the user.
Moves .ui and generated .py to a `views` folder. Three reasons: 1) the generated files should never import anything, so it's fine if they're in their own folder. 2) There were too many files in the application folder. 3) This improves project organization greatly IMO.

image

### CODE REVIEW

**Comment by runnersaw** [comment]
Usage would look like: `self.message_helper.show_message('hello')` from MainGUI

**Review by dcelik — COMMENTED** [review]
Looks good! I think we should merge the changes first, and then modify the file structure as this is causing large merge errors.

**Comment by runnersaw** [comment]
@dcelik it's up to date with dev now, and there are no other PRs at the moment, so I'm going to leave this, and hopefully we can get this approved before it conflicts with anything else ;)

**Review by dcelik — APPROVED** [review]
Perfect! Lets get this done now ;)

**Pull request merged**
