### PR TITLE
Fix lots of bugs

### PR DESCRIPTION
**Pull request by runnersaw**
Fixes for:

1. Fix for writing to a feature_video when it was open in QMediaPlayer (#108)
2. Stop printing annoying `config_path was None` messages
3. Fix if there is no `'error_message'` in the `'error'` dictionary
4. Remove the old video_frame_player now that QMediaPlayer works on Qt5
5. Fix a crash when trying to show an error message on project creation

### CODE REVIEW

**Review by dcelik — APPROVED** [review]
LGTM

**Comment by runnersaw** [comment]
Now fixes multiprocess things on Windows when packaging. See [here](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing).

**Review by dcelik — APPROVED** [review]
LGTM. Take a look at my changes then we can ship when you approve.

**Comment by runnersaw** [comment]
LGTM, merging.

**Pull request merged**
